# Generated by Django 6.0.6 on 2026-06-26 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('yaml_content', models.TextField()),
                ('persona', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('assertions', models.JSONField(default=list)),
                ('rubric', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio')], default='text', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='agents.agent')),
                ('call', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_run', to='agents.call')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='testing.scenario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passed', models.BooleanField(default=False)),
                ('transcript', models.JSONField(default=list)),
                ('assertion_results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='testing.testrun')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('reasoning', models.TextField()),
                ('passed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='testing.testresult')),
            ],
            options={
                'unique_together': {('test_result', 'field')},
            },
        ),
    ]
