# Generated by Django 6.0.6 on 2026-06-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='observer_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
