# Generated by Django 6.0.6 on 2026-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='greeting',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='yaml_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
