# Generated by Django 6.0.6 on 2026-06-26 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('gt', 'Gt'), ('lt', 'Lt'), ('gte', 'Gte'), ('lte', 'Lte'), ('eq', 'Eq')], max_length=5)),
                ('threshold', models.FloatField()),
                ('webhook_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('metric_value', models.FloatField()),
                ('payload_sent', models.JSONField(default=dict)),
                ('alert_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoring.alertconfig')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='agents.call')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
