# Generated by Django 5.2.15 on 2026-06-28 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multitenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('system_prompt', models.TextField()),
                ('greeting', models.TextField(blank=True, default='')),
                ('voice_id', models.CharField(blank=True, default='', max_length=255)),
                ('yaml_content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('gt', 'Gt'), ('lt', 'Lt'), ('gte', 'Gte'), ('lte', 'Lte'), ('eq', 'Eq')], max_length=5)),
                ('threshold', models.FloatField()),
                ('webhook_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='voice_qa.agent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('human', 'Human'), ('test_text', 'Test Text'), ('test_audio', 'Test Audio')], default='human', max_length=20)),
                ('daily_room_url', models.URLField(blank=True, default='')),
                ('daily_room_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='voice_qa.agent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_value', models.FloatField()),
                ('payload_sent', models.JSONField(default=dict)),
                ('alert_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='voice_qa.alertconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='voice_qa.call')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='voice_qa.call')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('yaml_content', models.TextField()),
                ('persona', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('assertions', models.JSONField(default=list)),
                ('rubric', models.JSONField(default=dict)),
                ('compatible_agents', models.JSONField(default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantAPIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passed', models.BooleanField(default=False)),
                ('transcript', models.JSONField(default=list)),
                ('assertion_results', models.JSONField(default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('reasoning', models.TextField()),
                ('passed', models.BooleanField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='voice_qa.testresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio')], default='text', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('observer_url', models.URLField(blank=True, default='', max_length=500)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='voice_qa.agent')),
                ('call', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_run', to='voice_qa.call')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='voice_qa.scenario')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='voice_qa.testrun'),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turns', models.JSONField(default=list)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='voice_qa.call')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant'], name='voice_qa_ag_tenant__9e18dd_idx'),
        ),
        migrations.AddIndex(
            model_name='alertconfig',
            index=models.Index(fields=['tenant'], name='voice_qa_al_tenant__a2ee98_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['tenant'], name='voice_qa_ca_tenant__75f9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['tenant'], name='voice_qa_al_tenant__dd71af_idx'),
        ),
        migrations.AddIndex(
            model_name='callmetric',
            index=models.Index(fields=['tenant'], name='voice_qa_ca_tenant__ce72e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='callmetric',
            unique_together={('call', 'name')},
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['tenant'], name='voice_qa_sc_tenant__bbc7ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='tenantapikey',
            index=models.Index(fields=['tenant'], name='voice_qa_te_tenant__593e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='judgescore',
            index=models.Index(fields=['tenant'], name='voice_qa_ju_tenant__18f85b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='judgescore',
            unique_together={('test_result', 'field')},
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['tenant'], name='voice_qa_te_tenant__5501c4_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['tenant'], name='voice_qa_te_tenant__9eb453_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['tenant'], name='voice_qa_tr_tenant__e50fa4_idx'),
        ),
    ]
