# Generated by Django 5.2.15 on 2026-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
