# Generated by Django 5.2.15 on 2026-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_qa', '0002_testrun_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='compatible_agents',
        ),
        migrations.AddField(
            model_name='scenario',
            name='compatible_agents',
            field=models.ManyToManyField(blank=True, related_name='compatible_scenarios', to='voice_qa.agent'),
        ),
    ]
