# Generated by Django 5.2.15 on 2026-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_qa', '0003_remove_scenario_compatible_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='el_agent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='target_type',
            field=models.CharField(choices=[('builtin', 'Built-in (Pipecat)'), ('elevenlabs', 'Remote ElevenLabs agent')], default='builtin', max_length=20),
        ),
    ]
