# Generated by Django 5.2.15 on 2026-06-30 04:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenant', '0002_alter_tenant_id'),
        ('voice_qa', '0004_agent_el_agent_id_agent_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevenLabsCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.TextField()),
                ('key_hint', models.CharField(blank=True, default='', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='multitenant.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['tenant'], name='voice_qa_el_tenant__ecac63_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_el_credential_per_tenant')],
            },
        ),
    ]
