# Generated by Django 5.2.15 on 2026-06-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_qa', '0005_elevenlabscredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='disconnect_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
