# Generated by Django 5.2.15 on 2026-06-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_qa', '0006_testrun_disconnect_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='live_scores',
            field=models.JSONField(default=dict),
        ),
    ]
