# Generated by Django 5.2.15 on 2026-06-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_qa', '0007_testrun_live_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='dynamic_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
